"use client"

import { createContext, useContext, useState, useEffect, type ReactNode } from "react"

type Language = "es" | "en"

type LanguageContextType = {
  language: Language
  setLanguage: (language: Language) => void
  t: (key: string) => string
}

const translations = {
  es: {
    dashboard: "Dashboard",
    welcome: "Bienvenido a tu panel financiero personal",
    accounts: "Cuentas",
    transactions: "Transacciones",
    budgets: "Presupuestos",
    settings: "Configuración",
    help: "Ayuda",
    income: "Ingresos",
    expense: "Gastos",
    balance: "Balance",
    cards: "Tarjetas",
    quickEntry: "Registro Rápido",
    addTransaction: "Añade rápidamente un ingreso o gasto",
    operationsSummary: "Resumen de Operaciones",
    recentTransactions: "Transacciones Recientes",
    recentTransactionsOverview: "Vista general de tus últimas transacciones",
    viewAll: "Ver todas",
    viewAllTransactions: "Ver todas las transacciones",
    amount: "Monto",
    category: "Categoría",
    account: "Cuenta",
    date: "Fecha",
    description: "Descripción",
    save: "Guardar",
    cancel: "Cancelar",
    newTransaction: "Nueva Transacción",
    type: "Tipo",
    selectType: "Selecciona el tipo",
    selectCategory: "Selecciona una categoría",
    selectAccount: "Selecciona una cuenta",
    selectDate: "Selecciona una fecha",
    food: "Alimentación",
    transport: "Transporte",
    housing: "Vivienda",
    entertainment: "Ocio",
    health: "Salud",
    salary: "Salario",
    other: "Otros",
    checkingAccount: "Cuenta Corriente",
    savingsAccount: "Cuenta de Ahorros",
    newAccount: "Nueva Cuenta",
    createNewAccount: "Crear Nueva Cuenta",
    accountName: "Nombre de la cuenta",
    add: "Añadir",
    optionalDescription: "Descripción (opcional)",
    transactionRegistered: "Transacción registrada",
    registeredSuccessfully: "registrado correctamente",
    accountCreated: "Cuenta creada",
    createdSuccessfully: "creada correctamente",
    changeTheme: "Cambiar tema",
    user: "Usuario",
    profile: "Perfil",
    logout: "Cerrar sesión",
    openMenu: "Abrir menú",
    selectIcon: "Seleccionar icono",
    searchIcons: "Buscar iconos",
    noIconsFound: "No se encontraron iconos",
    newCategory: "Nueva Categoría",
    createNewCategory: "Crear Nueva Categoría",
    categoryName: "Nombre de la categoría",
    categoryCreated: "Categoría creada",
    installApp: "Instalar aplicación",
    support: "Soporte",
    customizeDashboard: "Personalizar Dashboard",
    dragWidgets: "Arrastra los widgets para reorganizarlos",
    resizeWidgets: "Redimensiona los widgets según tus preferencias",
    gridView: "Vista de cuadrícula",
    listView: "Vista de lista",
    all: "Todas",
    search: "Buscar...",
    noTransactionsFound: "No se encontraron transacciones",
    expensesByCategory: "Gastos por Categoría",
    distributionOfExpenses: "Distribución de gastos",
    incomeVsExpenses: "Ingresos vs Gastos",
    monthlyComparison: "Comparación mensual",
    savingsTrend: "Tendencia de Ahorro",
    monthlySavingsEvolution: "Evolución mensual del ahorro",
    budgetProgress: "Progreso del Presupuesto",
    actualVsPlanned: "Gasto actual vs. planeado",
    accountBalances: "Saldos de Cuentas",
    balanceEvolution: "Evolución del saldo",
    selectPeriod: "Seleccionar periodo",
    thisWeek: "Esta semana",
    thisMonth: "Este mes",
    thisQuarter: "Este trimestre",
    thisYear: "Este año",
    lastQuarter: "Último trimestre",
    lastSixMonths: "Últimos 6 meses",
    lastYear: "Último año",
    allCategories: "Todas las categorías",
    currentSpending: "Gasto actual",
    limit: "Límite",
    allAccounts: "Todas las cuentas",
    totalBalance: "Saldo total",
    monthlyBalance: "Saldo mensual",
    financialAnalysis: "Análisis Financiero",
    customizeCharts: "Personalizar Gráficos",
    selectChartsToDisplay: "Selecciona los gráficos que deseas mostrar",
    done: "Listo",
    registerIncomeOrExpense: "Registra un nuevo ingreso o gasto",
    saveTransaction: "Guardar Transacción",
    // Nuevas traducciones
    manageYourCards: "Gestiona tus tarjetas de crédito y débito",
    newCard: "Nueva Tarjeta",
    totalCreditLimit: "Límite de Crédito Total",
    acrossAllCards: "En todas las tarjetas",
    currentDebt: "Deuda actual",
    nextPayment: "Próximo Pago",
    dueIn: "Vence en",
    days: "días",
    creditCards: "Tarjetas de Crédito",
    debitCards: "Tarjetas de Débito",
    noDebitCards: "No tienes tarjetas de débito registradas",
    card: "Tarjeta",
    bank: "Banco",
    dueDate: "Fecha de Vencimiento",
    usage: "Uso",
    actions: "Acciones",
    noCardsFound: "No se encontraron tarjetas",
    addNewCard: "Añadir Nueva Tarjeta",
    enterCardDetails: "Introduce los detalles de la tarjeta",
    cardName: "Nombre de la Tarjeta",
    enterCardName: "Introduce el nombre de la tarjeta",
    enterBankName: "Introduce el nombre del banco",
    cardType: "Tipo de Tarjeta",
    selectCardType: "Selecciona el tipo de tarjeta",
    creditLimit: "Límite de Crédito",
    currency: "Moneda",
    selectCurrency: "Selecciona una moneda",
    addCard: "Añadir Tarjeta",
    cardAdded: "Tarjeta añadida",
    manageYourPreferences: "Gestiona tus preferencias y configuración",
    general: "General",
    appearance: "Apariencia",
    notifications: "Notificaciones",
    security: "Seguridad",
    export: "Exportar",
    generalSettings: "Configuración General",
    generalSettingsDescription: "Gestiona tu información personal y preferencias",
    name: "Nombre",
    enterYourName: "Introduce tu nombre",
    nameDescription: "Este es el nombre que se mostrará en tu perfil",
    email: "Email",
    enterYourEmail: "Introduce tu email",
    emailDescription: "Este email se utilizará para notificaciones",
    language: "Idioma",
    selectLanguage: "Selecciona un idioma",
    languageDescription: "Idioma de la interfaz de usuario",
    defaultCurrency: "Moneda Predeterminada",
    currencyDescription: "Se utilizará para mostrar los importes",
    dateFormat: "Formato de Fecha",
    selectDateFormat: "Selecciona un formato de fecha",
    dateFormatDescription: "Formato para mostrar las fechas",
    saveChanges: "Guardar Cambios",
    settingsSaved: "Configuración guardada",
    yourSettingsHaveBeenSaved: "Tu configuración ha sido guardada correctamente",
    appearanceSettings: "Configuración de Apariencia",
    appearanceSettingsDescription: "Personaliza la apariencia de la aplicación",
    theme: "Tema",
    light: "Claro",
    dark: "Oscuro",
    system: "Sistema",
    themeDescription: "Selecciona el tema de la aplicación",
    appearanceUpdated: "Apariencia actualizada",
    yourAppearanceSettingsHaveBeenUpdated: "Tu configuración de apariencia ha sido actualizada",
    notificationSettings: "Configuración de Notificaciones",
    notificationSettingsDescription: "Gestiona cómo y cuándo recibes notificaciones",
    emailNotifications: "Notificaciones por Email",
    emailNotificationsDescription: "Recibe notificaciones importantes por email",
    pushNotifications: "Notificaciones Push",
    pushNotificationsDescription: "Recibe notificaciones en tiempo real",
    monthlyReports: "Informes Mensuales",
    monthlyReportsDescription: "Recibe un resumen mensual de tus finanzas",
    budgetAlerts: "Alertas de Presupuesto",
    budgetAlertsDescription: "Recibe alertas cuando te acerques a tu límite de presupuesto",
    paymentReminders: "Recordatorios de Pago",
    paymentRemindersDescription: "Recibe recordatorios de pagos próximos",
    notificationSettingsUpdated: "Configuración de notificaciones actualizada",
    yourNotificationSettingsHaveBeenUpdated: "Tu configuración de notificaciones ha sido actualizada",
    securitySettings: "Configuración de Seguridad",
    securitySettingsDescription: "Gestiona tu contraseña y seguridad de la cuenta",
    currentPassword: "Contraseña Actual",
    newPassword: "Nueva Contraseña",
    confirmPassword: "Confirmar Contraseña",
    passwordRequirements: "La contraseña debe tener al menos 8 caracteres",
    twoFactorAuthentication: "Autenticación de Dos Factores",
    twoFactorAuthenticationDescription: "Añade una capa extra de seguridad a tu cuenta",
    updatePassword: "Actualizar Contraseña",
    securitySettingsUpdated: "Configuración de seguridad actualizada",
    yourSecuritySettingsHaveBeenUpdated: "Tu configuración de seguridad ha sido actualizada",
    exportData: "Exportar Datos",
    exportDataDescription: "Exporta tus datos financieros en diferentes formatos",
    dataType: "Tipo de Datos",
    selectDataType: "Selecciona el tipo de datos",
    allData: "Todos los Datos",
    exportFormat: "Formato de Exportación",
    exportFormatDescription: "Selecciona el formato para exportar tus datos",
    dateRange: "Rango de Fechas",
    allTime: "Todo el Tiempo",
    customRange: "Rango Personalizado",
    startDate: "Fecha de Inicio",
    endDate: "Fecha de Fin",
    exportStarted: "Exportación iniciada",
    yourDataIsBeingExported: "Tus datos se están exportando",
    from: "Desde",
    to: "Hasta",
    showing: "Mostrando",
    of: "de",
    previous: "Anterior",
    next: "Siguiente",
    filters: "Filtros",
    resetFilters: "Restablecer filtros",
    transactionsHistory: "Historial de transacciones",
    allTypes: "Todos los tipos",
    categories: "Categorías",
    edit: "Editar",
    delete: "Eliminar",
    manageYourAccounts: "Gestiona tus cuentas bancarias y tarjetas",
    addNewAccount: "Añadir Nueva Cuenta",
    enterAccountDetails: "Introduce los detalles de la cuenta",
    accountType: "Tipo de Cuenta",
    selectAccountType: "Selecciona un tipo de cuenta",
    initialBalance: "Saldo Inicial",
    enterAccountName: "Introduce el nombre de la cuenta",
    icon: "Icono",
    accountAdded: "Cuenta añadida",
    investmentAccount: "Cuenta de Inversión",
    bankAccounts: "Cuentas Bancarias",
    activeAccounts: "cuentas activas",
    activeCards: "tarjetas activas",
    manageYourBudgets: "Gestiona tus presupuestos mensuales",
    newBudget: "Nuevo Presupuesto",
    createNewBudgetDescription: "Crea un nuevo presupuesto para controlar tus gastos",
    limitAmount: "Monto Límite",
    period: "Periodo",
    monthly: "Mensual",
    yearly: "Anual",
    saveBudget: "Guardar Presupuesto",
    budget: "Presupuesto",
    budgetCreated: "Presupuesto creado",
    hasBeenCreatedSuccessfully: "ha sido creado correctamente",
    searchCards: "Buscar tarjetas",
    myAccounts: "Mis Cuentas",
    manageYourBankAccountsAndCreditCards: "Administra tus cuentas bancarias y tarjetas de crédito",
    currencies: "Monedas",
    currencySettings: "Configuración de Monedas",
    manageCurrenciesAndExchangeRates: "Gestiona tus monedas y tipos de cambio",
    availableCurrencies: "Monedas Disponibles",
    manageYourCurrencies: "Gestiona tus monedas",
    addCurrency: "Agregar Moneda",
    code: "Código",
    symbol: "Símbolo",
    exchangeRate: "Tipo de Cambio",
    primaryCurrency: "Moneda Principal",
    visible: "Visible",
    editCurrency: "Editar Moneda",
    addNewCurrency: "Agregar Nueva Moneda",
    enterCurrencyDetails: "Ingresa los detalles de la moneda",
    currencyCode: "Código de Moneda",
    threeLetterISOCode: "Código ISO de tres letras",
    currencyName: "Nombre de Moneda",
    currencySymbol: "Símbolo de Moneda",
    exchangeRateDescription: "Tipo de cambio respecto a {currency}",
    primaryCurrencyDescription: "Esta moneda se usará como referencia para todas las conversiones",
    visibleCurrency: "Moneda Visible",
    visibleCurrencyDescription: "Mostrar esta moneda en la interfaz (máximo 2)",
    updateCurrency: "Actualizar Moneda",
    currencyAdded: "Moneda Agregada",
    hasBeenAddedSuccessfully: "ha sido agregada correctamente",
    currencyUpdated: "Moneda Actualizada",
    hasBeenUpdatedSuccessfully: "ha sido actualizada correctamente",
    currencyDeleted: "Moneda Eliminada",
    currencyHasBeenDeletedSuccessfully: "La moneda ha sido eliminada correctamente",
    cannotDeletePrimaryCurrency: "No se puede eliminar la moneda principal",
    pleaseSelectAnotherPrimaryCurrencyFirst: "Por favor, selecciona otra moneda principal primero",
    maximumVisibleCurrenciesReached: "Máximo de monedas visibles alcanzado",
    youCanOnlyHaveTwoVisibleCurrencies: "Solo puedes tener dos monedas visibles",
    primaryCurrencyChanged: "Moneda Principal Cambiada",
    exchangeRatesHaveBeenRecalculated: "Los tipos de cambio han sido recalculados",
    last3Months: "Últimos 3 meses",
    applyFilters: "Aplicar Filtros",
    desde: "Desde",
    hasta: "Hasta",
  },
  en: {
    dashboard: "Dashboard",
    welcome: "Welcome to your personal finance dashboard",
    accounts: "Accounts",
    transactions: "Transactions",
    budgets: "Budgets",
    settings: "Settings",
    help: "Help",
    income: "Income",
    expense: "Expenses",
    balance: "Balance",
    cards: "Cards",
    quickEntry: "Quick Entry",
    addTransaction: "Quickly add an income or expense",
    operationsSummary: "Operations Summary",
    recentTransactions: "Recent Transactions",
    recentTransactionsOverview: "Overview of your latest transactions",
    viewAll: "View all",
    viewAllTransactions: "View all transactions",
    amount: "Amount",
    category: "Category",
    account: "Account",
    date: "Date",
    description: "Description",
    save: "Save",
    cancel: "Cancel",
    newTransaction: "New Transaction",
    type: "Type",
    selectType: "Select type",
    selectCategory: "Select a category",
    selectAccount: "Select an account",
    selectDate: "Select a date",
    food: "Food",
    transport: "Transport",
    housing: "Housing",
    entertainment: "Entertainment",
    health: "Health",
    salary: "Salary",
    other: "Other",
    checkingAccount: "Checking Account",
    savingsAccount: "Savings Account",
    newAccount: "New Account",
    createNewAccount: "Create New Account",
    accountName: "Account name",
    add: "Add",
    optionalDescription: "Description (optional)",
    transactionRegistered: "Transaction registered",
    registeredSuccessfully: "registered successfully",
    accountCreated: "Account created",
    createdSuccessfully: "created successfully",
    changeTheme: "Change theme",
    user: "User",
    profile: "Profile",
    logout: "Logout",
    openMenu: "Open menu",
    selectIcon: "Select icon",
    searchIcons: "Search icons",
    noIconsFound: "No icons found",
    newCategory: "New Category",
    createNewCategory: "Create New Category",
    categoryName: "Category name",
    categoryCreated: "Category created",
    installApp: "Install app",
    support: "Support",
    customizeDashboard: "Customize Dashboard",
    dragWidgets: "Drag widgets to rearrange them",
    resizeWidgets: "Resize widgets according to your preferences",
    gridView: "Grid view",
    listView: "List view",
    all: "All",
    search: "Search...",
    noTransactionsFound: "No transactions found",
    expensesByCategory: "Expenses by Category",
    distributionOfExpenses: "Distribution of expenses",
    incomeVsExpenses: "Income vs Expenses",
    monthlyComparison: "Monthly comparison",
    savingsTrend: "Savings Trend",
    monthlySavingsEvolution: "Monthly savings evolution",
    budgetProgress: "Budget Progress",
    actualVsPlanned: "Actual vs. planned spending",
    accountBalances: "Account Balances",
    balanceEvolution: "Balance evolution",
    selectPeriod: "Select period",
    thisWeek: "This week",
    thisMonth: "This month",
    thisQuarter: "This quarter",
    thisYear: "This year",
    lastQuarter: "Last quarter",
    lastSixMonths: "Last 6 months",
    lastYear: "Last year",
    allCategories: "All categories",
    currentSpending: "Current spending",
    limit: "Limit",
    allAccounts: "All accounts",
    totalBalance: "Total balance",
    monthlyBalance: "Monthly balance",
    financialAnalysis: "Financial Analysis",
    customizeCharts: "Customize Charts",
    selectChartsToDisplay: "Select charts to display",
    done: "Done",
    registerIncomeOrExpense: "Register a new income or expense",
    saveTransaction: "Save Transaction",
    // New translations
    manageYourCards: "Manage your credit and debit cards",
    newCard: "New Card",
    totalCreditLimit: "Total Credit Limit",
    acrossAllCards: "Across all cards",
    currentDebt: "Current debt",
    nextPayment: "Next Payment",
    dueIn: "Due in",
    days: "days",
    creditCards: "Credit Cards",
    debitCards: "Debit Cards",
    noDebitCards: "You don't have any debit cards registered",
    card: "Card",
    bank: "Bank",
    dueDate: "Due Date",
    usage: "Usage",
    actions: "Actions",
    noCardsFound: "No cards found",
    addNewCard: "Add New Card",
    enterCardDetails: "Enter card details",
    cardName: "Card Name",
    enterCardName: "Enter card name",
    enterBankName: "Enter bank name",
    cardType: "Card Type",
    selectCardType: "Select card type",
    creditLimit: "Credit Limit",
    currency: "Currency",
    selectCurrency: "Select currency",
    addCard: "Add Card",
    cardAdded: "Card added",
    manageYourPreferences: "Manage your preferences and settings",
    general: "General",
    appearance: "Appearance",
    notifications: "Notifications",
    security: "Security",
    export: "Export",
    generalSettings: "General Settings",
    generalSettingsDescription: "Manage your personal information and preferences",
    name: "Name",
    enterYourName: "Enter your name",
    nameDescription: "This is the name that will be displayed on your profile",
    email: "Email",
    enterYourEmail: "Enter your email",
    emailDescription: "This email will be used for notifications",
    language: "Language",
    selectLanguage: "Select language",
    languageDescription: "User interface language",
    defaultCurrency: "Default Currency",
    currencyDescription: "Will be used to display amounts",
    dateFormat: "Date Format",
    selectDateFormat: "Select date format",
    dateFormatDescription: "Format for displaying dates",
    saveChanges: "Save Changes",
    settingsSaved: "Settings saved",
    yourSettingsHaveBeenSaved: "Your settings have been saved successfully",
    appearanceSettings: "Appearance Settings",
    appearanceSettingsDescription: "Customize the appearance of the application",
    theme: "Theme",
    light: "Light",
    dark: "Dark",
    system: "System",
    themeDescription: "Select the application theme",
    appearanceUpdated: "Appearance updated",
    yourAppearanceSettingsHaveBeenUpdated: "Your appearance settings have been updated",
    notificationSettings: "Notification Settings",
    notificationSettingsDescription: "Manage how and when you receive notifications",
    emailNotifications: "Email Notifications",
    emailNotificationsDescription: "Receive important notifications by email",
    pushNotifications: "Push Notifications",
    pushNotificationsDescription: "Receive real-time notifications",
    monthlyReports: "Monthly Reports",
    monthlyReportsDescription: "Receive a monthly summary of your finances",
    budgetAlerts: "Budget Alerts",
    budgetAlertsDescription: "Receive alerts when you approach your budget limit",
    paymentReminders: "Payment Reminders",
    paymentRemindersDescription: "Receive reminders for upcoming payments",
    notificationSettingsUpdated: "Notification settings updated",
    yourNotificationSettingsHaveBeenUpdated: "Your notification settings have been updated",
    securitySettings: "Security Settings",
    securitySettingsDescription: "Manage your password and account security",
    currentPassword: "Current Password",
    newPassword: "New Password",
    confirmPassword: "Confirm Password",
    passwordRequirements: "Password must be at least 8 characters long",
    twoFactorAuthentication: "Two-Factor Authentication",
    twoFactorAuthenticationDescription: "Add an extra layer of security to your account",
    updatePassword: "Update Password",
    securitySettingsUpdated: "Security settings updated",
    yourSecuritySettingsHaveBeenUpdated: "Your security settings have been updated",
    exportData: "Export Data",
    exportDataDescription: "Export your financial data in different formats",
    dataType: "Data Type",
    selectDataType: "Select data type",
    allData: "All Data",
    exportFormat: "Export Format",
    exportFormatDescription: "Select the format to export your data",
    dateRange: "Date Range",
    allTime: "All Time",
    startDate: "Start Date",
    endDate: "End Date",
    exportStarted: "Export started",
    yourDataIsBeingExported: "Your data is being exported",
    from: "From",
    to: "To",
    showing: "Showing",
    of: "of",
    previous: "Previous",
    next: "Next",
    filters: "Filters",
    resetFilters: "Reset filters",
    transactionsHistory: "Transactions history",
    allTypes: "All types",
    categories: "Categories",
    edit: "Edit",
    delete: "Delete",
    manageYourAccounts: "Manage your bank accounts and cards",
    addNewAccount: "Add New Account",
    enterAccountDetails: "Enter account details",
    accountType: "Account Type",
    selectAccountType: "Select account type",
    initialBalance: "Initial Balance",
    enterAccountName: "Enter account name",
    icon: "Icon",
    accountAdded: "Account added",
    investmentAccount: "Investment Account",
    bankAccounts: "Bank Accounts",
    activeAccounts: "active accounts",
    activeCards: "active cards",
    manageYourBudgets: "Manage your monthly budgets",
    newBudget: "New Budget",
    createNewBudgetDescription: "Create a new budget to control your expenses",
    limitAmount: "Limit Amount",
    period: "Period",
    monthly: "Monthly",
    yearly: "Yearly",
    saveBudget: "Save Budget",
    budget: "Budget",
    budgetCreated: "Budget created",
    hasBeenCreatedSuccessfully: "has been created successfully",
    searchCards: "Search cards",
    myAccounts: "My Accounts",
    manageYourBankAccountsAndCreditCards: "Manage your bank accounts and credit cards",
    currencies: "Currencies",
    currencySettings: "Currency Settings",
    manageCurrenciesAndExchangeRates: "Manage your currencies and exchange rates",
    availableCurrencies: "Available Currencies",
    manageYourCurrencies: "Manage your currencies",
    addCurrency: "Add Currency",
    code: "Code",
    symbol: "Symbol",
    exchangeRate: "Exchange Rate",
    primaryCurrency: "Primary Currency",
    visible: "Visible",
    editCurrency: "Edit Currency",
    addNewCurrency: "Add New Currency",
    enterCurrencyDetails: "Enter currency details",
    currencyCode: "Currency Code",
    threeLetterISOCode: "Three-letter ISO code",
    currencyName: "Currency Name",
    currencySymbol: "Currency Symbol",
    exchangeRateDescription: "Exchange rate relative to {currency}",
    primaryCurrencyDescription: "This currency will be used as a reference for all conversions",
    visibleCurrency: "Visible Currency",
    visibleCurrencyDescription: "Show this currency in the interface (maximum 2)",
    updateCurrency: "Update Currency",
    currencyAdded: "Currency Added",
    hasBeenAddedSuccessfully: "has been added successfully",
    currencyUpdated: "Currency Updated",
    hasBeenUpdatedSuccessfully: "has been updated successfully",
    currencyDeleted: "Currency Deleted",
    currencyHasBeenDeletedSuccessfully: "The currency has been deleted successfully",
    cannotDeletePrimaryCurrency: "Cannot delete primary currency",
    pleaseSelectAnotherPrimaryCurrencyFirst: "Please select another primary currency first",
    maximumVisibleCurrenciesReached: "Maximum visible currencies reached",
    youCanOnlyHaveTwoVisibleCurrencies: "You can only have two visible currencies",
    primaryCurrencyChanged: "Primary Currency Changed",
    exchangeRatesHaveBeenRecalculated: "Exchange rates have been recalculated",
    last3Months: "Last 3 months",
    customRange: "Custom Range",
    applyFilters: "Apply Filters",
    desde: "From",
    hasta: "To",
  },
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined)

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguageState] = useState<Language>("es")

  useEffect(() => {
    // Recuperar el idioma del localStorage si existe
    const savedLanguage = localStorage.getItem("language") as Language
    if (savedLanguage && ["es", "en"].includes(savedLanguage)) {
      setLanguageState(savedLanguage)
    }
  }, [])

  const setLanguage = (newLanguage: Language) => {
    setLanguageState(newLanguage)
    localStorage.setItem("language", newLanguage)
  }

  const t = (key: string): string => {
    return translations[language][key as keyof (typeof translations)[typeof language]] || key
  }

  return <LanguageContext.Provider value={{ language, setLanguage, t }}>{children}</LanguageContext.Provider>
}

export function useLanguage() {
  const context = useContext(LanguageContext)
  if (context === undefined) {
    throw new Error("useLanguage must be used within a LanguageProvider")
  }
  return context
}

